actualizacion Heroku 60

diff --git a/ayuntamiento/front/Dockerfile b/ayuntamiento/front/Dockerfile
--- a/ayuntamiento/front/Dockerfile
+++ b/ayuntamiento/front/Dockerfile
@@ -19,6 +19,13 @@ RUN npm run build
 # Configura una imagen más liviana para servir la aplicación
 FROM nginx:alpine
 
+RUN if [ -d "/app/dist/ayuntamiento" ]; then \
+      echo "Directorio 'ayuntamiento' encontrado."; \
+    else \
+      echo "ERROR: Directorio 'ayuntamiento' no encontrado."; \
+      exit 1; \
+    fi
+
 # Copia los archivos de compilación de Angular al directorio de Nginx
 COPY --from=build /app/dist/ayuntamiento /usr/share/nginx/html
 
